### ISSUE TITLE
file_get_contents(): Filename cannot be empty in [path]\vendor\docraptor\docraptor\lib\DocApi.php on line 395

### ISSUE THREAD

**Issue by mikenolan** [DocRaptor/docraptor-php#28]
Since upgrading to 3.0.0 I'm getting an error:
`file_get_contents(): Filename cannot be empty in path\vendor\docraptor\docraptor\lib\DocApi.php on line 395`

Changing `getRealpath` to `getPathname` fixes it. Suspect it might be because we're running PHP on a Windows server running IIS.

**Comment by esquivalient** [comment]
Thanks for reporting it! I'll test and get something out.

**Comment by esquivalient** [comment]
Changed in #29 and released in 3.0.1.
