### ISSUE TITLE
Javascript error in page causes generic "Error connecting to the API" message

### ISSUE THREAD

**Issue by airdrummingfool** [DocRaptor/docraptor-php#9]
Hello,
I'm working on setting up Docraptor, and kept getting the following error:

```
AN ERROR OCCURRED DURING EXECUTION; PLEASE TRY AGAIN LATER.
ADDITIONAL INFORMATION:
DOCRAPTOR\APIEXCEPTION
File:
[...]/vendor/docraptor/docraptor/lib/ApiClient.php:249
Message:
[422] Error connecting to the API (https://docraptor.com//docs)
```

Eventually I figured out that it wasn't an actual connection error, and discovered that debug mode could output to a file. Once I turned that on, I found the following in the debug response:

``` xml
[DEBUG] HTTP Response body ~BEGIN~
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error>[Javascript Error] ReferenceError: Can't find variable: L</error>
  <error>[Javascript Error] document:642</error>
</errors>

~END~
```

So, it turns out that Docraptor _could_ connect to the API, it was just running into some JS errors on my page. It would be very helpful if these errors were reported in the exception that gets thrown, instead of throwing a generic "error connecting to the API" message.

**Comment by jqr** [comment]
Yeah that's confusing, thanks for reporting this!

**Comment by rsands2801** [comment]
@jqr Any update on this issue as its a major bug that prevents the library being much use?

**Comment by jqr** [comment]
@rsands2801 We're aware of the issue and looking at better ways to implement this feature across all of our clients. In the mean time, it's still quite functional(it's our second most used library) just a bit more tedious if you run into JavaScript errors.

**Comment by AlexOverbeck** [comment]
Hi everyone, I should be able to help out here. First, I'd like to start by recommending an update to the latest version of our package _(currently [v2.0.0](https://packagist.org/packages/docraptor/docraptor))_.

There are two common ways to figure out what happened in the event that DocRaptor encounters an issue when generating a document. I'll give an example of both below that should cover your specific use case. Depending on the kind of document you are generating one of the following should help improve error handling.

_**Note:** Both of these examples should work as written when using v2.0.0 of our package. If you are using an older version a similar pattern will still work, but you might have to make some minor tweaks. I'm happy to help here as well._

### Synchronous documents _(the default)_
When creating a document synchronously, any non-2xx [http status code](https://docraptor.com/documentation/api#api_status_codes) will result in a `DocRaptor\ApiException`.

```php
$contentWithError = <<<EOT
  <html>
    <body>
      <h1>Hello from PHP</h1>
      <script>
        const heading = document.querySelector('h1');
        SYNTAX_ERROR // We want this to cause a syntax error
        heading.style.color = "blue";
      </script>
    </body>
  </html>
EOT;

$docraptor = new DocRaptor\DocApi();
$docraptor->getConfig()->setUsername("YOUR_API_KEY_HERE");

$doc = new DocRaptor\Doc();
$doc->setName("php-sync.pdf");
$doc->setTest(true);
$doc->setJavascript(true);
$doc->setDocumentType("pdf");
$doc->setDocumentContent($contentWithError);

try {
  $response = $docraptor->createDoc($doc);
} catch (DocRaptor\ApiException $exception) {
  echo $exception->getCode() . "\n";
  echo $exception->getResponseBody() . "\n";
}
```

The above example will result in the following output:
```
422
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error>[Javascript Error] ReferenceError: Can't find variable: SYNTAX_ERROR</error>
  <error>[Javascript Error] Mon Aug 10 2020 19:26:57 GMT+0000 (UTC)</error>
  <error>[Javascript Error] undefined:6 in global code</error>
  <error>[Javascript Error] :0 in setContent</error>
</errors>
```

### Asynchronous documents
When creating and asynchronous document you will not know the status of the document until you request it. When the DocRaptor encounters and issue in this case it will result in a "failed" status.

```php
$contentWithError = <<<EOT
  <html>
    <body>
      <h1>Hello from PHP</h1>
      <script>
        const heading = document.querySelector('h1');
        SYNTAX_ERROR // We want this to cause a syntax error
        heading.style.color = "blue";
      </script>
    </body>
  </html>
EOT;

$docraptor = new DocRaptor\DocApi();
$docraptor->getConfig()->setUsername("YOUR_API_KEY_HERE");

$doc = new DocRaptor\Doc();
$doc->setName("php-sync.pdf");
$doc->setTest(true);
$doc->setJavascript(true);
$doc->setDocumentType("pdf");
$doc->setDocumentContent($contentWithError);

$response = $docraptor->createAsyncDoc($doc);

for($i=0; $i<30; $i++) {
  $status_response = $docraptor->getAsyncDocStatus($response->getStatusId());
  switch ($status_response->getStatus()) {
    case "completed":
      $doc_response = $docraptor->getAsyncDoc($status_response->getDownloadId());
      break;
    case "failed":
      echo($status_response->getValidationErrors());
      break;
    default:
      sleep(1);
  }
}
```
The above asynchronous example will result in the following output:

```
[Javascript Error] ReferenceError: Can't find variable: SYNTAX_ERROR
[Javascript Error] Mon Aug 10 2020 19:42:48 GMT+0000 (UTC)
[Javascript Error] undefined:6 in global code
[Javascript Error] :0 in setContentPASS javascript.php
```
